version: "3.9"

services:
  parse-dependency:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: .
        target: /data
    # # export as xml
    command: sh -c "cat /data/source_formatted.txt | cabocha -f3 -o /data/parsed.xml"
    # export as lattice
    # command: sh -c "cat /data/source_formatted.txt | cabocha -f1 -o /data/parsed.txt"
    # export as tree
    # command: sh -c "cat /data/source_formatted.txt | cabocha -f0 -o /data/tree.txt"
